name = "cfmgr"
compatibility_date = "2024-12-01"
main = "src/index.ts"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "cfmgr"
database_id = "4aada139-54fb-4725-9789-031500f31b0c"

[[kv_namespaces]]
binding = "KV"
id = "65a21fab872646cc91b0772a6af521f4"

[vars]
API_SECRET = ""
ENCRYPTION_KEY = ""
DEMO_ACCOUNT_IDS = ""
